%% Inizialization symbolic variables.
syms t alpha(t) ...
       xi xi_d xi_dd ...
       d c a0 ...
       K I ...
       CD MAC L l0 Omega...
       P1 P2...
       A_orf A_c V0...
       Cd rho rhoA Beta ...
       F_imp ...
       T_1 T_2 ...
       P_10 P_20 T_10 T_20 rho_0 Beta_0 DP DT ...
       Q1_in Q1_out Q2_in Q2_out

%% Definition of kinematic variables of the plunger of the lead-lag damper.
Script_Kinematics;

%% Definition of fluid density variables.
Script_rho;

%% Definition of blade and plunger of the lead-lag damber dynamics variables.
Script_BladeDynamics;

%% Equilibrium.
StaticEquilibrium;

%% Relief Valve.
Script_ReliefValve;

%% Definition of flow and pressure dynamics variables.
Script_PressureDynamics;
